name: "PushSources"
on:
 push:
   branches:
     - master
jobs:
  push-sources-for-translation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: 'checkout'
      - uses: applanga/setup-applanga-cli@v1.0.0
        with:
          version: 1.0.47
      - name: Push translations to Applanga
        run: applanga push --force
        working-directory: checkout
